const categories = [
  { name: 'Accessories', _id: 0, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Airport seating', _id: 1, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Café tables', _id: 2, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Care sets', _id: 3, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Chairs', _id: 4, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Chaises Longues', _id: 5, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Clocks', _id: 6, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Coat Racks & Wall Shelves', _id: 7, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Coffee and Side Tables', _id: 8, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Conference Systems and Tables', _id: 9, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Decorative Objects', _id: 10, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Desks', _id: 11, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Dining Tables', _id: 12, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Lighting', _id: 13, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Lounge Chairs', _id: 14, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Micro Architecture', _id: 15, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Office Chairs', _id: 16, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Office Furniture Systems', _id: 17, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Organisers & Small Storage', _id: 18, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Publications', _id: 19, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Sculptures', _id: 20, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Sofas', _id: 21, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Spare Parts', _id: 22, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Stools Benches and Ottomans', _id: 23, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Storage', _id: 24, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Tables', _id: 25, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Textiles', _id: 26, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Trays & Vessels', _id: 27, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Vases & Planters', _id: 28, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
  { name: 'Visitor and Conference Chairs', _id: 29, avatar: 'https://static.vitra.com/media-resized/NfC4_Aebx0IUAwLwRlRJUpORtztBNq5LFOxAJktx9x4/fill/0/1020/ce/0/aHR0cHM6Ly9zdGF0aWMudml0cmEuY29tL21lZGlhL2Fzc2V0Lzc5NjYxOTUvc3RvcmFnZS92X2Z1bGxibGVlZF8xNDQweC83Nzc4NDcxNC5qcGc.jpg', description: 'A number of Vitra chairs are icons of twentieth-century furniture design and have been produced by the company for over fifty years, while other models embody the spirit of contemporary innovation. But all are distinguished by the harmonious interplay of function, form and material.' },
]

class Api {
  get = async query => {
    return categories
  }

  getById = async id => {
    return categories.filter(e => e._id == id)
  }

  findOne = async query => {
    return categories.filter(e => Object.keys(query).every(key => query[key] == e[key]))[0]
  }
}


export default new Api()